### ISSUE TITLE
Light and Dark Theme

### ISSUE THREAD

**Issue by Ankurcr7** [Ankurcr7/Editor.md#8]
### I want to make a button which will trigger a`(example - theme)` function whose work will be to toggle between light and dark theme. 

```javascript
const theme = () => {
    // code
}
```

#### NOTE: It should not reset the theme after changing the page nor after refreshing the page!

**Comment by Sengpai** [comment]
can i started your project has an assignee?

**Comment by Ankurcr7** [comment]
@Sengpai Yes, Thank you for helping.

**Comment by NhutTuanB2112021** [comment]
Can you assign me to work this issue?

**Comment by Ankurcr7** [comment]
@NhutTuanB2112021 Yes, Thank you for helping.

**Comment by Sengpai** [comment]
hey although i solved this issue but i committed without tag of issue so which did not close, i will write some comment lines in code and please merge it, this is a part of document for me at school.

**Comment by Ankurcr7** [comment]
@Sengpai @NhutTuanB2112021 This issue is completed... So, no need to work on this issue. And sorry @NhutTuanB2112021 for not assigning you to this issue.

**Comment by Sengpai** [comment]
@Ankurcr7 i need you merge my last commit to this issue closed, so i can take a screen shoot for my Presentation material.

**Comment by Ankurcr7** [comment]
@Sengpai I merged it. I hope it will help you with your document at school.

**Comment by Ankurcr7** [comment]
Now I am closing this issue. Thank you for your contribution.
